global using Cafestore.Domain.Entities.Assortment;
global using Cafestore.Domain.Entities.Order;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Cafestore.Persistance.CafestoreDb.EntityTypeConfiguration;
global using Cafestore.Persistance.CafestoreDb;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Cafestore.Domain.Abstractions;